name: Kurtosis Integration Tests

on:
  # Allow manual trigger
  workflow_dispatch:
  # Run nightly at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

jobs:
  integration-tests:
    name: Run Kurtosis Integration Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install Contender
        run: bash scripts/ci/kurtosis.sh install-contender

      - name: Install Kurtosis
        run: bash scripts/ci/kurtosis.sh install

      - name: Deploy Optimism Package
        run: bash scripts/ci/kurtosis.sh deploy

      - name: Run Integration Tests
        run: bash scripts/ci/kurtosis.sh run
